Fix errors of too few hooks rendered by moving useState and useInput out of conditions in PartialList
Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.

https://stackoverflow.com/questions/53472795/uncaught-error-rendered-fewer-hooks-than-expected-this-may-be-caused-by-an-acc